outputMode: active
scale: 1
background:
  red: 0.156
  green: 0.164
  blue: 0.210
  opacity: 0.9
widget:
  margin:
    margins: [20, 20, 20, 20]
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins: [0, 88, 0, 32]
                widget:
                  verticalLayout:
                    - date:
                        font_size: 48.0
                    - clock:
                        font_size: 128.0
            - verticalLayout:
                - margin:
                    margins: [0, 0, 0, 8]
                    widget:
                      pulseAudio:
                        font_size: 24.0
                        length: 600
        - calendar:
            font_size: 16.0
            sections: 3
        - launcher:
            font_size: 32.0
            length: 1200
            app_opener: "swaymsg exec "
            term_opener: "alacritty -e "
            url_opener: "xdg-open "
